"""
PolyTASwapRSI Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import PolyTASwapRSIStrategy
except ImportError:
    from strategy import PolyTASwapRSIStrategy

__all__ = [
    "PolyTASwapRSIStrategy",
]
